version: 2.1
orbs:
  altostra-orb: altostra/altostra-orb@1.1.0
  node: circleci/node@4.1.1

jobs:
  push-and-deploy-image:
    parameters:
      env-name:
        type: string
        default: "Dev"
        description: "Env to deploy to"
      instance-name:
        type: string
        default: "dev"
        description: "Env to deploy to"

    docker:
      - image: cimg/node:12.19
    environment:
      VERSION_NANE: "<< pipeline.git.branch >>-<< pipeline.git.revision >>"
    steps:
      - checkout
      - node/install-packages
      - run: |
          echo "Pushing version: $VERSION_NANE"
      - altostra-orb/setup
      - altostra-orb/push:
          image-name: $VERSION_NANE
      - altostra-orb/deploy-version:
          env-name: << parameters.env-name >>
          instance-name: << parameters.instance-name >>
          image-name: "$VERSION_NANE"

workflows:
  test-push:
    jobs:
      - node/test:
          context:
            - altostra-demo #this should include the NPM_TOKEN should you need it to auth with custom images
          version: "12.19"
      - push-and-deploy-image:
          context:
            - altostra-demo
          requires:
            - node/test
