version: 2.1
orbs:
  altostra-orb: altostra/altostra-orb@1.1.0
  node: circleci/node@4.1.1

jobs:
  push-and-deploy-image:
    parameters:
      alto-version:
        type: integer
      env-name:
        type: string
        default: "Dev"
        description: "Env to deploy to"
      instance-name:
        type: string
        default: "dev"
        description: "Env to deploy to"

    docker:
      - image: cimg/node:12.19
    steps:
      - checkout
      - node/install-packages
      - altostra-orb/setup
      - altostra-orb/deploy-version:
          env-name: << parameters.env-name >>
          instance-name: << parameters.instance-name >>
          image-name: "<< pipeline.git.branch >>-<< pipeline.project.git_url >>"

workflows:
  test-push:
    jobs:
      - node/test:
          context:
            - altostra-demo #this should include the NPM_TOKEN should you need it to auth with custom images
          version: "12.19"
      - push-and-deploy-image:
          alto-version: 1.1.1
          context:
            - altostra-demo
          requires:
            - node/test